module.exports = {
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        dash: {
          "primary": "#1e40af",
          "secondary": "#166534",
          "accent": "#fecaca",
          "neutral": "#374151",
          "base-100": "#ffffff",
          "info": "#bfdbfe",
          "success": "#00ffff",
          "warning": "#fef08a",
          "error": "#7f1d1d",
          "--rounded-btn": "1.9rem",
          "--tab-border": "2px",
          "--tab-radius": "0.7rem",
        },
      },
      'light',
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
};
